# Generated by Django 5.0.10 on 2024-12-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_lv2_cate_2_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='prod_name',
            new_name='product',
        ),
    ]
